#reference: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
#reference to expressions https://docs.github.com/en/enterprise-cloud@latest/actions/reference/workflows-and-actions/expressions

name: output_info
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        run: echo "${{ toJson(github) }}"